services:
  streamlit:
    container_name: langchain-streamlit
    build: .
    ports:
      - "8501:8501"
    environment:
      QDRANT_URL: http://qdrant
      QDRANT_COLLECTION_NAME: store_collection

      LANGCHAIN_TRACING_V2: true
      LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
      LANGCHAIN_API_KEY: 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
      LANGCHAIN_PROJECT: chat_langchain

      OLLAMA_MODEL: llama3-groq-tool-use
      OLLAMA_HOST: http://ollama:11434

    depends_on:
      - qdrant
      - ollama

  qdrant:
    container_name: langchain-qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ~/data/qdrant-db:/qdrant/storage:z

  ollama:
    container_name: langchain-ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    pull_policy: always
    tty: true
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
